# Generated by Django 3.0.3 on 2020-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=24, unique=True)),
                ('movie_overview', models.CharField(max_length=264, unique=True)),
                ('movie_id', models.IntegerField(max_length=24, unique=True)),
                ('movie_release_date', models.IntegerField(max_length=4, unique=True)),
            ],
        ),
    ]
