# Generated by Django 3.0.3 on 2020-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundmovie',
            name='movie_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='foundmovie',
            name='movie_release_date',
            field=models.IntegerField(unique=True),
        ),
    ]
